[project]
name = "learn_influences"
version = "0.1.0"
description = "Add a short description here"
authors = ["Etienne Tack <5456949+etiennetack@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
model = "python ./model/main.py"
learn = "python ./model/learn/main.py"

[dependencies]
python = ">=3.12.5,<3.13"
mesa = ">=2.1.5,<2.2"
mesa-geo = ">=0.7.1,<0.8"
rasterio = ">=1.3.11,<1.4"
pymoo = ">=0.6.1.3,<0.6.2"
shapely = ">=2.0.6,<2.1"
scikit-learn = ">=1.5.2,<1.6"
aiohttp = ">=3.10.5,<3.11"
toml = ">=0.10.2,<0.11"
jupyterlab = ">=4.2.5,<4.3"
seaborn = ">=0.13.2,<0.14"
pyarrow = ">=17.0.0,<17.1"
pendulum = ">=3.0.0,<3.1"
python-socketio = ">=5.11.4,<5.12"
nptyping = ">=2.5.0,<2.6"
rioxarray = ">=0.17.0,<0.18"
